### ISSUE TITLE
Noosphere FS FFI panics when cannot open sphere

### ISSUE THREAD

**Issue by gordonbrander** [subconsciousnetwork/noosphere#206]
Encountered while integrating Noosphere with app.

Error messages:

```
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: No value found for 'identity'', rust/noosphere/src/ffi/fs.rs:73:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Error, attempted to panic across the FFI boundary of `ns_sphere_fs_open()`, which is Undefined Behavior.
Aborting for soundness.
```

and

```
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: No value found for 'user_key_name'', rust/noosphere/src/ffi/fs.rs:73:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Error, attempted to panic across the FFI boundary of `ns_sphere_fs_open()`, which is Undefined Behavior.
Aborting for soundness.
```

**Comment by gordonbrander** [comment]
If we did something like log return `null` when sphere cannot be opened, it would let me handle the failure gracefully on the Swift side.
